### ISSUE TITLE
bad registered Cupronickel blocks and items

### ISSUE THREAD

**Issue by 0Navis0** [EXTER7/BaseMaterials#28]
It's impossible to switch between ImmeriveEngineering Constantan and Substratum Cupronichel block,  nugget, slab, and plate for recipes and in ore dictionnary converter while it's possible with ingot and dust. I suppose they are bad registered in ore dictionnary. https://github.com/BluSunrize/ImmersiveEngineering/issues/1691

**Comment by EXTER7** [comment]
Blocks now register with alternate Ore Dictionary names in Substratum 1.8.2.1. Note that by default Ore Dictionary Converter will  only convert certain items such as ores, ingots, dusts, and blocks. To enable conversion for more items you need to edit the ODC config file (fodc.conf) to add entries to the whitelist.
To be able to convert to convert IE constantan to Substratum cupronickel, the entry "*.Cupronickel" needs to be added to the ODC black-list, this is needed because ODC requires all ore dictionary names for an item to be the same, but IE constantan is registered as "*Constantan" while Substratum cupronickel is registered as both "*Cupronickel" and "*Constantan".

The fodc.conf should look similar to the following:
```
general {

    B:log_names=false

    S:blacklist=.*Cupronickel

    S:whitelist=^ore.*,^ingot.*,^dust.*,^block.*,^plate.*,^gear.*,^rod.*,^nugget.*,^slab.*
}
```
